In [21]:
import pandas as pd

In [22]:
data = pd.read_csv("../backend/dataset/indian_water_physicochemical_parameters.csv", encoding = 'unicode_escape')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data

STATION CODE                                         LOCATIONS  \
0          1393.0                     DAMANGANGA AT D/S OF MADHUBAN   
1          1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER   
2          1865.0                           RIVER DHADAR AT KOTHADA   
3          1149.0                              KOLAK AT PATALIA BDG   
4          1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS   
..            ...                                               ...   
733        2052.0                           TUIRIAL UPPER CATCHMENT   
734        2053.0                           TUIRIAL LOWER CATCHMENT   
735        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA   
736        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA   
737        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA   

           STATE  Temp  D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  \
0    DAMAN & DIU  31.0          7.1  7.8                     151.0   
1        GUJARAT  28.0          7.2  7.4                     319.0   
2        GUJARAT  27.0          6.2  8.4                     894.0   
3        GUJARAT  29.0          2.4  7.6                    1500.0   
4            GOA  31.0          5.9  7.2                      52.0   
..           ...   ...          ...  ...                       ...   
733      MIZORAM  23.6          6.9  7.1                     186.0   
734      MIZORAM  23.5          6.8  7.1                     201.0   
735      TRIPURA  27.3          6.2  7.8                     165.0   
736      TRIPURA  29.1          6.4  7.8                     158.0   
737      TRIPURA  26.6          6.6  7.9                     210.0   

     B.O.D. (mg/l)  NITRATENAN N+ NITRITENANN (mg/l)  \
0              8.0                              0.08   
1              0.7                              0.18   
2              9.0                              0.38   
3              6.2                              1.31   
4              2.1                              0.08   
..             ...                               ...   
733            1.6                              0.10   
734            1.4                              0.20   
735            2.1                              0.00   
736            4.1                              0.50   
737            4.2                              1.90   

     FECAL COLIFORM (MPN/100ml)  TOTAL COLIFORM (MPN/100ml)Mean  year  \
0                         233.0                           465.0  2012   
1                           5.0                            10.0  2012   
2                         140.0                           350.0  2012   
3                           3.0                            13.0  2012   
4                         233.0                            90.0  2012   
..                          ...                             ...   ...   
733                       233.0                            29.0  2014   
734                       233.0                            86.0  2014   
735                       282.0                           340.0  2014   
736                       458.0                           500.0  2014   
737                       510.0                           572.0  2014   

           date  
0    2012-01-01  
1    2012-01-04  
2    2012-01-05  
3    2012-01-06  
4    2012-01-07  
..          ...  
733  2014-12-22  
734  2014-12-24  
735  2014-12-25  
736  2014-12-26  
737  2014-12-27  

[738 rows x 13 columns]

In [23]:
temp = data["Temp"].values
print(type(temp[0]))
temp

<class 'numpy.float64'>


array([31. , 28. , 27. , 29. , 31. , 30. , 30. , 29. , 29. , 29. , 28. ,
       30. , 30. , 27. , 28. , 29. , 28. , 29. , 29. , 30. , 28. , 28. ,
       29. , 28. , 30. , 30. , 31. , 29. , 30. , 29. , 29. , 29. , 29. ,
       30. , 27. , 27. , 27. , 23. , 29. , 29. , 29. , 28. , 29. , 29. ,
       29. , 29. , 30. , 30. , 29. , 25. , 30. , 30. , 31. , 30. , 30. ,
       28. , 28. , 28. , 27. , 27. , 26. , 27. , 28. , 23. , 22. , 23. ,
       26. , 26. , 26. , 26. , 26. , 26. , 29. , 28. , 28. , 29. , 26. ,
       26. , 28. , 29. , 26. , 26. , 25. , 29. , 29. , 25. , 27. , 27. ,
       29. , 29. , 29. , 27. , 30. , 27. , 27. , 25. , 25. , 26. , 29. ,
       27. , 27. , 27. , 28. , 26. , 29. , 27. , 28. , 29. , 28. , 29. ,
       26. , 28. , 28. , 28. , 28. , 27. , 28. , 28. , 28. , 28. , 28. ,
       28. , 26. , 28. , 29. , 28. , 26. , 29. , 29. , 27. , 29. , 27. ,
       27. , 20. , 24. , 28. , 27. , 32. , 30. , 22. , 22. , 24. , 27. ,
       26. , 25. , 28. , 26. , 28. , 31. , 25. , 25

In [24]:
dates = data["date"].values
print(type(dates[0]))
dates

<class 'str'>


array(['2012-01-01', '2012-01-04', '2012-01-05', '2012-01-06',
       '2012-01-07', '2012-01-10', '2012-01-13', '2012-01-15',
       '2012-01-16', '2012-01-17', '2012-01-18', '2012-01-20',
       '2012-01-22', '2012-01-23', '2012-01-26', '2012-01-27',
       '2012-01-28', '2012-02-02', '2012-02-04', '2012-02-05',
       '2012-02-06', '2012-02-10', '2012-02-11', '2012-02-12',
       '2012-02-13', '2012-02-15', '2012-02-16', '2012-02-18',
       '2012-02-19', '2012-02-20', '2012-02-21', '2012-02-22',
       '2012-02-24', '2012-02-25', '2012-02-27', '2012-03-01',
       '2012-03-02', '2012-03-03', '2012-03-04', '2012-03-05',
       '2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
       '2012-03-10', '2012-03-11', '2012-03-12', '2012-03-14',
       '2012-03-16', '2012-03-17', '2012-03-18', '2012-03-19',
       '2012-03-20', '2012-03-22', '2012-03-23', '2012-03-24',
       '2012-03-26', '2012-03-27', '2012-03-28', '2012-04-01',
       '2012-04-02', '2012-04-04', '2012-04-05', '2012-

In [25]:
dict_ = dict(zip(dates, data["Temp"].values))


In [26]:
dict_

{'2012-01-01': 31.0,
 '2012-01-04': 28.0,
 '2012-01-05': 27.0,
 '2012-01-06': 29.0,
 '2012-01-07': 31.0,
 '2012-01-10': 30.0,
 '2012-01-13': 30.0,
 '2012-01-15': 29.0,
 '2012-01-16': 29.0,
 '2012-01-17': 29.0,
 '2012-01-18': 28.0,
 '2012-01-20': 30.0,
 '2012-01-22': 30.0,
 '2012-01-23': 27.0,
 '2012-01-26': 28.0,
 '2012-01-27': 29.0,
 '2012-01-28': 28.0,
 '2012-02-02': 29.0,
 '2012-02-04': 29.0,
 '2012-02-05': 30.0,
 '2012-02-06': 28.0,
 '2012-02-10': 28.0,
 '2012-02-11': 29.0,
 '2012-02-12': 28.0,
 '2012-02-13': 30.0,
 '2012-02-15': 30.0,
 '2012-02-16': 31.0,
 '2012-02-18': 29.0,
 '2012-02-19': 30.0,
 '2012-02-20': 29.0,
 '2012-02-21': 29.0,
 '2012-02-22': 29.0,
 '2012-02-24': 29.0,
 '2012-02-25': 30.0,
 '2012-02-27': 27.0,
 '2012-03-01': 27.0,
 '2012-03-02': 27.0,
 '2012-03-03': 23.0,
 '2012-03-04': 29.0,
 '2012-03-05': 29.0,
 '2012-03-06': 29.0,
 '2012-03-07': 28.0,
 '2012-03-08': 29.0,
 '2012-03-09': 29.0,
 '2012-03-10': 29.0,
 '2012-03-11': 29.0,
 '2012-03-12': 30.0,
 '2012-03-14'

In [27]:
data.describe()

STATION CODE        Temp  D.O. (mg/l)          PH  \
count    736.000000  738.000000   738.000000  738.000000   
mean    2252.947011   26.228320     6.583198    7.290379   
std      813.619235    3.323943     1.063475    0.440368   
min       17.000000   17.000000     2.400000    5.600000   
25%     1567.000000   24.075000     6.100000    7.000000   
50%     2297.000000   27.000000     6.700000    7.300000   
75%     2877.250000   28.875000     7.200000    7.600000   
max     3473.000000   33.000000     9.900000    8.400000   

       CONDUCTIVITY (µmhos/cm)  B.O.D. (mg/l)  \
count                738.000000     738.000000   
mean                 909.699187       3.694537   
std                 2574.757652       6.421942   
min                   30.000000       0.100000   
25%                   74.250000       1.200000   
50%                  144.000000       1.800000   
75%                  352.750000       3.100000   
max                18569.000000      88.000000   

       NITRATENAN N+ NITRITENANN (mg/l)  FECAL COLIFORM (MPN/100ml)  \
count                        738.000000                  738.000000   
mean                           1.279350                 2128.460705   
std                            1.768243                 6397.810887   
min                            0.000000                    2.000000   
25%                            0.250000                   30.000000   
50%                            0.545000                  233.000000   
75%                            1.580000                  616.750000   
max                           11.810000                53083.000000   

       TOTAL COLIFORM (MPN/100ml)Mean         year  
count                      738.000000   738.000000  
mean                      3947.182927  2012.943089  
std                      11161.052236     0.816726  
min                          0.000000  2012.000000  
25%                         67.000000  2012.000000  
50%                        420.000000  2013.000000  
75%                       1556.750000  2014.000000  
max                      87167.000000  2014.000000

In [28]:
dict_temp = dict(zip(dates, data["Temp"].values))
dict_do = dict(zip(dates, data["D.O. (mg/l)"].values))
dict_ph = dict(zip(dates, data["PH"].values))
dict_conductivity = dict(zip(dates, data["CONDUCTIVITY (µmhos/cm)"].values))
dict_bod = dict(zip(dates, data["B.O.D. (mg/l)"].values))
dict_nitra = dict(zip(dates, data["NITRATENAN N+ NITRITENANN (mg/l)"].values))
dict_fecal = dict(zip(dates, data["FECAL COLIFORM (MPN/100ml)"].values))


In [29]:
dict_temp

{'2012-01-01': 31.0,
 '2012-01-04': 28.0,
 '2012-01-05': 27.0,
 '2012-01-06': 29.0,
 '2012-01-07': 31.0,
 '2012-01-10': 30.0,
 '2012-01-13': 30.0,
 '2012-01-15': 29.0,
 '2012-01-16': 29.0,
 '2012-01-17': 29.0,
 '2012-01-18': 28.0,
 '2012-01-20': 30.0,
 '2012-01-22': 30.0,
 '2012-01-23': 27.0,
 '2012-01-26': 28.0,
 '2012-01-27': 29.0,
 '2012-01-28': 28.0,
 '2012-02-02': 29.0,
 '2012-02-04': 29.0,
 '2012-02-05': 30.0,
 '2012-02-06': 28.0,
 '2012-02-10': 28.0,
 '2012-02-11': 29.0,
 '2012-02-12': 28.0,
 '2012-02-13': 30.0,
 '2012-02-15': 30.0,
 '2012-02-16': 31.0,
 '2012-02-18': 29.0,
 '2012-02-19': 30.0,
 '2012-02-20': 29.0,
 '2012-02-21': 29.0,
 '2012-02-22': 29.0,
 '2012-02-24': 29.0,
 '2012-02-25': 30.0,
 '2012-02-27': 27.0,
 '2012-03-01': 27.0,
 '2012-03-02': 27.0,
 '2012-03-03': 23.0,
 '2012-03-04': 29.0,
 '2012-03-05': 29.0,
 '2012-03-06': 29.0,
 '2012-03-07': 28.0,
 '2012-03-08': 29.0,
 '2012-03-09': 29.0,
 '2012-03-10': 29.0,
 '2012-03-11': 29.0,
 '2012-03-12': 30.0,
 '2012-03-14'

In [30]:
from collections import defaultdict
from datetime import datetime
import calendar

def calculate_monthly_mean(data):
    # Create a defaultdict to store measurements for each month for each year
    yearly_monthly_data = defaultdict(lambda: defaultdict(list))

    # Iterate through the data and add measurements to the corresponding month and year
    for date_str, value in data.items():
        date = datetime.strptime(date_str, "%Y-%m-%d")
        year = date.year
        month = date.month
        yearly_monthly_data[year][month].append(value)

    mean_data = {}
    for year, monthly_data in yearly_monthly_data.items():
        mean_data[year] = {}
        for month, values in monthly_data.items():
            month_name = calendar.month_name[month]
            mean_data[year][month_name] = sum(values) / len(values)

    return mean_data


In [31]:
calculate_monthly_mean(dict_temp).values()

dict_values([{'January': 29.0, 'February': 29.11111111111111, 'March': 28.5, 'April': 26.53846153846154, 'May': 27.391304347826086, 'June': 27.8, 'July': 26.041666666666668, 'August': 24.384615384615383, 'September': 26.545454545454547, 'October': 29.647058823529413, 'November': 23.82608695652174, 'December': 21.82608695652174}, {'January': 28.345, 'February': 29.18571428571429, 'March': 27.782608695652176, 'April': 26.354999999999997, 'May': 27.46470588235294, 'June': 27.671428571428578, 'July': 27.92631578947368, 'August': 25.268421052631584, 'September': 25.736363636363635, 'October': 24.809090909090912, 'November': 21.334999999999997, 'December': 21.79}, {'January': 29.45, 'February': 29.070588235294125, 'March': 26.238888888888887, 'April': 26.59047619047619, 'May': 27.610526315789468, 'June': 27.53, 'July': 27.98888888888889, 'August': 25.57777777777778, 'September': 24.960869565217386, 'October': 24.13529411764706, 'November': 21.157142857142862, 'December': 22.233333333333334}]

In [56]:
from scipy.stats import zscore
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn import neural_network

In [120]:
data = pd.read_csv("../backend/dataset/indian_water_physicochemical_parameters.csv", encoding = 'unicode_escape')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data['date'] = pd.to_datetime(data['date'])
data

STATION CODE                                         LOCATIONS  \
0          1393.0                     DAMANGANGA AT D/S OF MADHUBAN   
1          1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER   
2          1865.0                           RIVER DHADAR AT KOTHADA   
3          1149.0                              KOLAK AT PATALIA BDG   
4          1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS   
..            ...                                               ...   
733        2052.0                           TUIRIAL UPPER CATCHMENT   
734        2053.0                           TUIRIAL LOWER CATCHMENT   
735        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA   
736        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA   
737        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA   

           STATE  Temp  D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  \
0    DAMAN & DIU  31.0          7.1  7.8                     151.0   
1        GUJARAT  28.0          7.2  7.4                     319.0   
2        GUJARAT  27.0          6.2  8.4                     894.0   
3        GUJARAT  29.0          2.4  7.6                    1500.0   
4            GOA  31.0          5.9  7.2                      52.0   
..           ...   ...          ...  ...                       ...   
733      MIZORAM  23.6          6.9  7.1                     186.0   
734      MIZORAM  23.5          6.8  7.1                     201.0   
735      TRIPURA  27.3          6.2  7.8                     165.0   
736      TRIPURA  29.1          6.4  7.8                     158.0   
737      TRIPURA  26.6          6.6  7.9                     210.0   

     B.O.D. (mg/l)  NITRATENAN N+ NITRITENANN (mg/l)  \
0              8.0                              0.08   
1              0.7                              0.18   
2              9.0                              0.38   
3              6.2                              1.31   
4              2.1                              0.08   
..             ...                               ...   
733            1.6                              0.10   
734            1.4                              0.20   
735            2.1                              0.00   
736            4.1                              0.50   
737            4.2                              1.90   

     FECAL COLIFORM (MPN/100ml)  TOTAL COLIFORM (MPN/100ml)Mean  year  \
0                         233.0                           465.0  2012   
1                           5.0                            10.0  2012   
2                         140.0                           350.0  2012   
3                           3.0                            13.0  2012   
4                         233.0                            90.0  2012   
..                          ...                             ...   ...   
733                       233.0                            29.0  2014   
734                       233.0                            86.0  2014   
735                       282.0                           340.0  2014   
736                       458.0                           500.0  2014   
737                       510.0                           572.0  2014   

          date  
0   2012-01-01  
1   2012-01-04  
2   2012-01-05  
3   2012-01-06  
4   2012-01-07  
..         ...  
733 2014-12-22  
734 2014-12-24  
735 2014-12-25  
736 2014-12-26  
737 2014-12-27  

[738 rows x 13 columns]

In [121]:
# Set the 'date' column as the index
data.set_index('date', inplace=True)

# Specify the date you want to find the index for
specified_date = '2012-01-01'

# Get the index of the specified date
index_of_date = data.index.get_loc(specified_date)

print("Index of the specified date '{}' is: {}".format(specified_date, index_of_date))

Index of the specified date '2012-01-01' is: 0


In [78]:
data['date'] = pd.to_datetime(data['date'])
df = data.drop(columns=["STATION CODE", "LOCATIONS", "STATE", "Temp", "year", "date"])
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

In [79]:
df

D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  B.O.D. (mg/l)  \
0            7.1  7.8                     151.0            8.0   
1            7.2  7.4                     319.0            0.7   
2            6.2  8.4                     894.0            9.0   
3            2.4  7.6                    1500.0            6.2   
4            5.9  7.2                      52.0            2.1   
..           ...  ...                       ...            ...   
733          6.9  7.1                     186.0            1.6   
734          6.8  7.1                     201.0            1.4   
735          6.2  7.8                     165.0            2.1   
736          6.4  7.8                     158.0            4.1   
737          6.6  7.9                     210.0            4.2   

     NITRATENAN N+ NITRITENANN (mg/l)  FECAL COLIFORM (MPN/100ml)  \
0                                0.08                       233.0   
1                                0.18                         5.0   
2                                0.38                       140.0   
3                                1.31                         3.0   
4                                0.08                       233.0   
..                                ...                         ...   
733                              0.10                       233.0   
734                              0.20                       233.0   
735                              0.00                       282.0   
736                              0.50                       458.0   
737                              1.90                       510.0   

     TOTAL COLIFORM (MPN/100ml)Mean  
0                             465.0  
1                              10.0  
2                             350.0  
3                              13.0  
4                              90.0  
..                              ...  
733                            29.0  
734                            86.0  
735                           340.0  
736                           500.0  
737                           572.0  

[738 rows x 7 columns]

In [80]:
df.fillna(df.median(), inplace=True)
# Checking for outliers
z_scores = df.apply(zscore)
outliers_count = (z_scores.abs() > 3).sum()
df_outliers = np.where(np.abs(z_scores) > 3)[0]
print(outliers_count)
df_filtered = df.drop(df.index[df_outliers])
df_filtered


D.O. (mg/l)                         13
PH                                   2
CONDUCTIVITY (µmhos/cm)            26
B.O.D. (mg/l)                       22
NITRATENAN N+ NITRITENANN (mg/l)    15
FECAL COLIFORM (MPN/100ml)          25
TOTAL COLIFORM (MPN/100ml)Mean      28
dtype: int64


D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  B.O.D. (mg/l)  \
0            7.1  7.8                     151.0            8.0   
1            7.2  7.4                     319.0            0.7   
2            6.2  8.4                     894.0            9.0   
4            5.9  7.2                      52.0            2.1   
5            6.1  6.8                     408.0            1.3   
..           ...  ...                       ...            ...   
733          6.9  7.1                     186.0            1.6   
734          6.8  7.1                     201.0            1.4   
735          6.2  7.8                     165.0            2.1   
736          6.4  7.8                     158.0            4.1   
737          6.6  7.9                     210.0            4.2   

     NITRATENAN N+ NITRITENANN (mg/l)  FECAL COLIFORM (MPN/100ml)  \
0                                0.08                       233.0   
1                                0.18                         5.0   
2                                0.38                       140.0   
4                                0.08                       233.0   
5                                0.17                      1300.0   
..                                ...                         ...   
733                              0.10                       233.0   
734                              0.20                       233.0   
735                              0.00                       282.0   
736                              0.50                       458.0   
737                              1.90                       510.0   

     TOTAL COLIFORM (MPN/100ml)Mean  
0                             465.0  
1                              10.0  
2                             350.0  
4                              90.0  
5                            3808.0  
..                              ...  
733                            29.0  
734                            86.0  
735                           340.0  
736                           500.0  
737                           572.0  

[659 rows x 7 columns]

In [84]:
X = df_filtered.iloc[:,:7].values
print(X)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

[[7.10e+00 7.80e+00 1.51e+02 ... 8.00e-02 2.33e+02 4.65e+02]
 [7.20e+00 7.40e+00 3.19e+02 ... 1.80e-01 5.00e+00 1.00e+01]
 [6.20e+00 8.40e+00 8.94e+02 ... 3.80e-01 1.40e+02 3.50e+02]
 ...
 [6.20e+00 7.80e+00 1.65e+02 ... 0.00e+00 2.82e+02 3.40e+02]
 [6.40e+00 7.80e+00 1.58e+02 ... 5.00e-01 4.58e+02 5.00e+02]
 [6.60e+00 7.90e+00 2.10e+02 ... 1.90e+00 5.10e+02 5.72e+02]]


array([[ 0.42160387,  1.14833701, -0.27730426, ..., -0.76368175,
        -0.29257625, -0.30916859],
       [ 0.53655503,  0.23740822, -0.1056815 , ..., -0.68517274,
        -0.38057367, -0.40615524],
       [-0.61295655,  2.51473018,  0.48171783, ..., -0.52815473,
        -0.32846993, -0.3336817 ],
       ...,
       [-0.61295655,  1.14833701, -0.26300236, ..., -0.82648895,
        -0.27366452, -0.33581327],
       [-0.38305424,  1.14833701, -0.27015331, ..., -0.43394393,
        -0.20573669, -0.30170808],
       [-0.15315192,  1.3760692 , -0.21703198, ...,  0.66518213,
        -0.1856671 , -0.28636074]])

In [65]:
# predict the water quality index based on a set of measurements
def predict_wqi(values):
    import joblib
    model = joblib.load('regressor_model.pkl')
    if(len(values.shape) == 1):
        values = values.reshape(1,-1)
    
    y_pred = model.predict(values)
    
    return y_pred


# determine the water quality class based on a wqi value
# the function takes an array
def get_wqc(wqi):
    import numpy as np
    wqc = []
    wqi = np.array(wqi)
    if(len(wqi.shape) == 0):
        wqi = wqi.reshape(1,-1)
        
    print(wqi)
        
    for i in range(wqi.shape[0]):
        if(wqi[i] <= 50):
            wqc.append("good")
        elif(wqi[i] <= 100):
            wqc.append("poor")
        else:
            wqc.append("unsuitable")
    return np.array(wqc)


In [93]:
X_scaled[1]

array([ 0.53655503,  0.23740822, -0.1056815 , -0.66423783, -0.68517274,
       -0.38057367, -0.40615524])

In [95]:
predict_wqi(X_scaled[1])

c:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator MLPRegressor from version 1.3.0 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


array([19.38327189])

In [92]:
get_wqc(predict_wqi(X_scaled[1]))

[19.38327212]


c:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator MLPRegressor from version 1.3.0 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


array(['good'], dtype='<U4')

In [126]:
data

STATION CODE                                         LOCATIONS  \
date                                                                         
2012-01-01        1393.0                     DAMANGANGA AT D/S OF MADHUBAN   
2012-01-04        1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER   
2012-01-05        1865.0                           RIVER DHADAR AT KOTHADA   
2012-01-06        1149.0                              KOLAK AT PATALIA BDG   
2012-01-07        1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS   
...                  ...                                               ...   
2014-12-22        2052.0                           TUIRIAL UPPER CATCHMENT   
2014-12-24        2053.0                           TUIRIAL LOWER CATCHMENT   
2014-12-25        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA   
2014-12-26        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA   
2014-12-27        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA   

                  STATE  Temp  D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  \
date                                                                        
2012-01-01  DAMAN & DIU  31.0          7.1  7.8                     151.0   
2012-01-04      GUJARAT  28.0          7.2  7.4                     319.0   
2012-01-05      GUJARAT  27.0          6.2  8.4                     894.0   
2012-01-06      GUJARAT  29.0          2.4  7.6                    1500.0   
2012-01-07          GOA  31.0          5.9  7.2                      52.0   
...                 ...   ...          ...  ...                       ...   
2014-12-22      MIZORAM  23.6          6.9  7.1                     186.0   
2014-12-24      MIZORAM  23.5          6.8  7.1                     201.0   
2014-12-25      TRIPURA  27.3          6.2  7.8                     165.0   
2014-12-26      TRIPURA  29.1          6.4  7.8                     158.0   
2014-12-27      TRIPURA  26.6          6.6  7.9                     210.0   

            B.O.D. (mg/l)  NITRATENAN N+ NITRITENANN (mg/l)  \
date                                                          
2012-01-01            8.0                              0.08   
2012-01-04            0.7                              0.18   
2012-01-05            9.0                              0.38   
2012-01-06            6.2                              1.31   
2012-01-07            2.1                              0.08   
...                   ...                               ...   
2014-12-22            1.6                              0.10   
2014-12-24            1.4                              0.20   
2014-12-25            2.1                              0.00   
2014-12-26            4.1                              0.50   
2014-12-27            4.2                              1.90   

            FECAL COLIFORM (MPN/100ml)  TOTAL COLIFORM (MPN/100ml)Mean  year  
date                                                                          
2012-01-01                       233.0                           465.0  2012  
2012-01-04                         5.0                            10.0  2012  
2012-01-05                       140.0                           350.0  2012  
2012-01-06                         3.0                            13.0  2012  
2012-01-07                       233.0                            90.0  2012  
...                                ...                             ...   ...  
2014-12-22                       233.0                            29.0  2014  
2014-12-24                       233.0                            86.0  2014  
2014-12-25                       282.0                           340.0  2014  
2014-12-26                       458.0                           500.0  2014  
2014-12-27                       510.0                           572.0  2014  

[738 rows x 12 columns]

In [124]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore

def wqi_gauge(specified_date):
    df = data.copy()
    print(df)
    df['date'] = pd.to_datetime(df['date'])
    df.set_index('date', inplace=True)
    index_of_date = df.index.get_loc(specified_date)
    
    df = df.drop(columns=["STATION CODE", "LOCATIONS", "STATE", "Temp", "year", "date"])
    
    for column in df.columns:
        df[column] = pd.to_numeric(df[column], errors='coerce')
        
    df.fillna(df.median(), inplace=True)
    
    # Checking for outliers in the full dfset
    z_scores = df.apply(zscore)
    outliers_count = (z_scores.abs() > 3).sum()
    df_outliers = np.where(np.abs(z_scores) > 3)[0]
    print(outliers_count)
    df_filtered = df.drop(df.index[df_outliers])
    
    # Scale the df
    scaler = StandardScaler()
    X = df_filtered.values
    X_scaled = scaler.fit_transform(X)
    
    return X_scaled[index_of_date]

In [125]:
wqi_gauge('2012-01-05')

            STATION CODE                                         LOCATIONS  \
date                                                                         
2012-01-01        1393.0                     DAMANGANGA AT D/S OF MADHUBAN   
2012-01-04        1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER   
2012-01-05        1865.0                           RIVER DHADAR AT KOTHADA   
2012-01-06        1149.0                              KOLAK AT PATALIA BDG   
2012-01-07        1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS   
...                  ...                                               ...   
2014-12-22        2052.0                           TUIRIAL UPPER CATCHMENT   
2014-12-24        2053.0                           TUIRIAL LOWER CATCHMENT   
2014-12-25        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA   
2014-12-26        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA   
2014-12-27        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVE

KeyError: 'date'

In [97]:
data = pd.read_csv("../backend/dataset/indian_water_physicochemical_parameters.csv", encoding = 'unicode_escape')
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data

STATION CODE                                         LOCATIONS  \
0          1393.0                     DAMANGANGA AT D/S OF MADHUBAN   
1          1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER   
2          1865.0                           RIVER DHADAR AT KOTHADA   
3          1149.0                              KOLAK AT PATALIA BDG   
4          1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS   
..            ...                                               ...   
733        2052.0                           TUIRIAL UPPER CATCHMENT   
734        2053.0                           TUIRIAL LOWER CATCHMENT   
735        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA   
736        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA   
737        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA   

           STATE  Temp  D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  \
0    DAMAN & DIU  31.0          7.1  7.8                     151.0   
1        GUJARAT  28.0          7.2  7.4                     319.0   
2        GUJARAT  27.0          6.2  8.4                     894.0   
3        GUJARAT  29.0          2.4  7.6                    1500.0   
4            GOA  31.0          5.9  7.2                      52.0   
..           ...   ...          ...  ...                       ...   
733      MIZORAM  23.6          6.9  7.1                     186.0   
734      MIZORAM  23.5          6.8  7.1                     201.0   
735      TRIPURA  27.3          6.2  7.8                     165.0   
736      TRIPURA  29.1          6.4  7.8                     158.0   
737      TRIPURA  26.6          6.6  7.9                     210.0   

     B.O.D. (mg/l)  NITRATENAN N+ NITRITENANN (mg/l)  \
0              8.0                              0.08   
1              0.7                              0.18   
2              9.0                              0.38   
3              6.2                              1.31   
4              2.1                              0.08   
..             ...                               ...   
733            1.6                              0.10   
734            1.4                              0.20   
735            2.1                              0.00   
736            4.1                              0.50   
737            4.2                              1.90   

     FECAL COLIFORM (MPN/100ml)  TOTAL COLIFORM (MPN/100ml)Mean  year  \
0                         233.0                           465.0  2012   
1                           5.0                            10.0  2012   
2                         140.0                           350.0  2012   
3                           3.0                            13.0  2012   
4                         233.0                            90.0  2012   
..                          ...                             ...   ...   
733                       233.0                            29.0  2014   
734                       233.0                            86.0  2014   
735                       282.0                           340.0  2014   
736                       458.0                           500.0  2014   
737                       510.0                           572.0  2014   

           date  
0    2012-01-01  
1    2012-01-04  
2    2012-01-05  
3    2012-01-06  
4    2012-01-07  
..          ...  
733  2014-12-22  
734  2014-12-24  
735  2014-12-25  
736  2014-12-26  
737  2014-12-27  

[738 rows x 13 columns]

In [98]:
df = data.drop(columns=["STATION CODE", "LOCATIONS", "STATE", "Temp", "year", "date"])


In [99]:
data

STATION CODE                                         LOCATIONS  \
0          1393.0                     DAMANGANGA AT D/S OF MADHUBAN   
1          1150.0          DAMANGANGA AT KACHIGAON U\S AT GIDC WIER   
2          1865.0                           RIVER DHADAR AT KOTHADA   
3          1149.0                              KOLAK AT PATALIA BDG   
4          1399.0  ZUARI AT D/S OF PT. WHERE KUMBARJRIA CANAL JOINS   
..            ...                                               ...   
733        2052.0                           TUIRIAL UPPER CATCHMENT   
734        2053.0                           TUIRIAL LOWER CATCHMENT   
735        1403.0                GUMTI AT U/S SOUTH TRIPURA,TRIPURA   
736        1404.0               GUMTI AT D/S SOUTH TRIPURA, TRIPURA   
737        1726.0  CHANDRAPUR, AGARTALA D/S OF HAORA RIVER, TRIPURA   

           STATE  Temp  D.O. (mg/l)   PH  CONDUCTIVITY (µmhos/cm)  \
0    DAMAN & DIU  31.0          7.1  7.8                     151.0   
1        GUJARAT  28.0          7.2  7.4                     319.0   
2        GUJARAT  27.0          6.2  8.4                     894.0   
3        GUJARAT  29.0          2.4  7.6                    1500.0   
4            GOA  31.0          5.9  7.2                      52.0   
..           ...   ...          ...  ...                       ...   
733      MIZORAM  23.6          6.9  7.1                     186.0   
734      MIZORAM  23.5          6.8  7.1                     201.0   
735      TRIPURA  27.3          6.2  7.8                     165.0   
736      TRIPURA  29.1          6.4  7.8                     158.0   
737      TRIPURA  26.6          6.6  7.9                     210.0   

     B.O.D. (mg/l)  NITRATENAN N+ NITRITENANN (mg/l)  \
0              8.0                              0.08   
1              0.7                              0.18   
2              9.0                              0.38   
3              6.2                              1.31   
4              2.1                              0.08   
..             ...                               ...   
733            1.6                              0.10   
734            1.4                              0.20   
735            2.1                              0.00   
736            4.1                              0.50   
737            4.2                              1.90   

     FECAL COLIFORM (MPN/100ml)  TOTAL COLIFORM (MPN/100ml)Mean  year  \
0                         233.0                           465.0  2012   
1                           5.0                            10.0  2012   
2                         140.0                           350.0  2012   
3                           3.0                            13.0  2012   
4                         233.0                            90.0  2012   
..                          ...                             ...   ...   
733                       233.0                            29.0  2014   
734                       233.0                            86.0  2014   
735                       282.0                           340.0  2014   
736                       458.0                           500.0  2014   
737                       510.0                           572.0  2014   

           date  
0    2012-01-01  
1    2012-01-04  
2    2012-01-05  
3    2012-01-06  
4    2012-01-07  
..          ...  
733  2014-12-22  
734  2014-12-24  
735  2014-12-25  
736  2014-12-26  
737  2014-12-27  

[738 rows x 13 columns]

In [109]:
import pandas as pd

# Assuming your data is stored in a DataFrame called data

# Convert the 'date' column to datetime format if it's not already in datetime format
data['date'] = pd.to_datetime(data['date'])

# Specify the date you want to extract data for
specified_date = '2012-01-05'  # Change this to your desired date

# Filter the DataFrame to get data for the specified date and create a copy
specified_date_data = data[data['date'] == specified_date].copy()

# Drop the specified columns
specified_date_data.drop(columns=['STATION CODE', 'LOCATIONS', 'STATE', 'Temp', 'year', 'date'], inplace=True)

# Print the modified data for the specified date
print(specified_date_data.values)


[[6.20e+00 8.40e+00 8.94e+02 9.00e+00 3.80e-01 1.40e+02 3.50e+02]]
